apiVersion: v1
kind: Pod
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  containers:
    - name: container-nodejs
      image: didox/app-imersao-docker-nodejs
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-nodejs
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000 # 30000 ~ 32767
  selector:
    app: nodejs