apiVersion: v1
kind: Pod
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  containers:
    - name: container-nodejs
      image: didox/app-imersao-docker-nodejs
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-nodejs
spec:
  type: ClusterIP
  selector:
    app: nodejs
  ports:
    - port: 3000
      targetPort: 3000