apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    upstream nodejs {
      server clusterip-nodejs:3000;
    }

    upstream csharp {
        server clusterip-csharp:5001;
    }

    server {
        proxy_set_header   Host            $http_host;
        proxy_set_header   Upgrade         $http_upgrade;
        proxy_set_header   X-Real-IP       $remote_addr;
        proxy_set_header   X-NginX-Proxy   true;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 30s;
        proxy_read_timeout 30s;

        listen 80;
        
        rewrite ^/nodejs/(.*)  /nodejs/$1;
        rewrite ^/csharp/(.*)  /csharp/$1;

        location /nodejs/ {
            proxy_pass http://nodejs/;
        }

        location /csharp/ {
            proxy_pass http://csharp/;
        }
    }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: default.conf
